/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.3.4, using .NET Server 2.3.0 template (version 8)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>

** Copyright (c) 2006-2015 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.3
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.3, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace OPCServer/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.3/
**
** Created: 22.03.2015
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace OPCServer
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class DataTypes
    {
    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class Objects
    {
    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class ObjectTypes
    {
        /// <summary>
        /// The identifier for the WeatherStationType ObjectType.
        /// </summary>
        public const uint WeatherStationType = 1001;

    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class Methods
    {
        /// <summary>
        /// The identifier for the getConditions Method.
        /// </summary>
        public const uint WeatherStationType_getConditions = 7001;

        /// <summary>
        /// The identifier for the getForecast Method.
        /// </summary>
        public const uint WeatherStationType_getForecast = 7002;

    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the Conditions Variable.
        /// </summary>
        public const uint WeatherStationType_Conditions = 6001;

        /// <summary>
        /// The identifier for the Forecast Variable.
        /// </summary>
        public const uint WeatherStationType_Forecast = 6010;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class MethodIds
    {
        /// <summary>
        /// The identifier for the WeatherStationType_getConditions Method.
        /// </summary>
        public static readonly ExpandedNodeId WeatherStationType_getConditions = new ExpandedNodeId(Methods.WeatherStationType_getConditions, Namespaces.OPCServer);

        /// <summary>
        /// The identifier for the WeatherStationType_getForecast Method.
        /// </summary>
        public static readonly ExpandedNodeId WeatherStationType_getForecast = new ExpandedNodeId(Methods.WeatherStationType_getForecast, Namespaces.OPCServer);

    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class ObjectIds
    {
    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class ObjectTypeIds
    {
        /// <summary>
        /// The identifier for the WeatherStationType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId WeatherStationType = new ExpandedNodeId(ObjectTypes.WeatherStationType, Namespaces.OPCServer);

    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the WeatherStationType_Conditions Variable.
        /// </summary>
        public static readonly ExpandedNodeId WeatherStationType_Conditions = new ExpandedNodeId(Variables.WeatherStationType_Conditions, Namespaces.OPCServer);

        /// <summary>
        /// The identifier for the WeatherStationType_Forecast Variable.
        /// </summary>
        public static readonly ExpandedNodeId WeatherStationType_Forecast = new ExpandedNodeId(Variables.WeatherStationType_Forecast, Namespaces.OPCServer);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares constants for all VariableType in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.3.4")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the Conditions component.
        /// </summary>
        public const string Conditions = "Conditions";
        /// <summary>
        /// The BrowseName for the Forecast component.
        /// </summary>
        public const string Forecast = "Forecast";
        /// <summary>
        /// The BrowseName for the WeatherStationType component.
        /// </summary>
        public const string WeatherStationType = "WeatherStationType";
        /// <summary>
        /// The BrowseName for the getConditions component.
        /// </summary>
        public const string getConditions = "getConditions";
        /// <summary>
        /// The BrowseName for the getForecast component.
        /// </summary>
        public const string getForecast = "getForecast";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the OPCServer namespace.
        /// </summary>
        public const string OPCServer = "OPCServer/";
    }
    #endregion
}
